apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://eoepca.github.io/helm-charts'
    chart: dummy
    targetRevision: 1.0.2
    helm:
      values: |
        ingress:
          enabled: true
      # parameters:
      #   - name: ingress.enabled
      #     value: 'true'
  destination:
    name: in-cluster
    # namespace: dummy
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
